name: Update M3U List
on:
  schedule:
    - cron: '0 */12 * * *'  # Her 12 saatte bir çalıştır (UTC zaman dilimi)
  workflow_dispatch:         # Manuel tetikleme seçeneği

jobs:
  update-m3u:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Fetch and Save M3U
        run: php fetch_m3u.php

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add kablotv_processed.m3u
          git commit -m "Auto-update M3U list [$(date +'%Y-%m-%d %H:%M')]"
          git push
