name: Update M3U List
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  update-m3u:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Tüm commit geçmişini çekmek için

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Fetch and Save M3U
        run: |
          php fetch_m3u.php
          ls -la  # Dosyanın oluştuğunu kontrol et

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add kablotv_processed.m3u
          git status  # Değişiklikleri göster
          git commit -m "Auto-update M3U [$(date +'%d.%m.%Y %H:%M')]"
          git push
