name: Update M3U List
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'  # Her 12 saatte bir (UTC)

jobs:
  update-m3u:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Fetch M3U
        run: python fetch_m3u.py

      - name: Upload Error Log (Debug)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: error-log
          path: error.log

      - name: Commit M3U
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add kablotv_processed.m3u
          git commit -m "Auto-update M3U [$(date +'%Y-%m-%d %H:%M')]"
          git push
